inference:
  device: cpu
  det_config: ./mmpose/projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py
  det_checkpoint: https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_nano_8xb32-100e_coco-obj365-person-05d8511e.pth
  pose_config: ./mmpose/projects/rtmpose/rtmpose/body_2d_keypoint/rtmpose-s_8xb256-420e_coco-256x192.py
  pose_checkpoint: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/rtmpose-s_simcc-aic-coco_pt-aic-coco_420e-256x192-fcb2599b_20230126.pth
  bbox_thr: 0.2
  nms_thr: 0.3
  draw_heatmap: False   # Draw heatmap predicted by the model
  det_cat_id: 0   # Category id for bounding box detection model
output_root: result
visualize:
  skeleton_style: mmpose
  radius: 3
  thickness: 1
  alpha: 0.8
  draw_bbox: False
  show_kpt_idx: False   # Whether to show the index of keypoints
  kpt_thr: 0.3
